name: apiverve_acrostic
description: Acrostic Puzzle Generator creates puzzles where the first letters of answer words spell out a hidden keyword.
version: 1.1.13
homepage: https://apiverve.com/marketplace/acrostic?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/acrostic-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
