// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.AcrosticPuzzleGenerator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("keyword")]
        public string Keyword { get; set; }

        [JsonProperty("theme")]
        public string Theme { get; set; }

        [JsonProperty("lines")]
        public Line[] Lines { get; set; }

        [JsonProperty("lineCount")]
        public long LineCount { get; set; }

        [JsonProperty("html")]
        public string Html { get; set; }
    }

    public partial class Line
    {
        [JsonProperty("position")]
        public long Position { get; set; }

        [JsonProperty("letter")]
        public string Letter { get; set; }

        [JsonProperty("answer")]
        public string Answer { get; set; }

        [JsonProperty("letterCount")]
        public long LetterCount { get; set; }

        [JsonProperty("clue")]
        public string Clue { get; set; }
    }
}
